spring.application.name=URL_Shortner

spring.datasource.driver-class-name=org.postgresql.Driver

# Using RDS for PostgresDB
spring.datasource.url=jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:Demos}
spring.datasource.username=${RDS_USERNAME:postgres}
spring.datasource.password=${RDS_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true

server.port=5000

# App config
app.url.alias.max.size=16
app.url.alias.min.size=3
app.base.url=${BASE_URL:http://localhost:8080}